rem SCHTASKS /Create /sc minute /mo 2 /tn "syncdata" /tr "D:\wamp64\www\amzcount\run.bat"
SCHTASKS /Create /sc daily /st 23:55:00 /tn "usasyncdata" /tr "D:\wamp64\www\amzcount\atuotask\usa_run.bat"
SCHTASKS /Create /sc daily /st 00:05:00 /tn "uksyncdata" /tr "D:\wamp64\www\amzcount\atuotask\uk_run.bat"
SCHTASKS /Create /sc daily /st 00:10:00 /tn "desyncdata" /tr "D:\wamp64\www\amzcount\atuotask\de_run.bat"
SCHTASKS /Create /sc daily /st 00:15:00 /tn "jpsyncdata" /tr "D:\wamp64\www\amzcount\atuotask\jp_run.bat"
SCHTASKS /Create /sc daily /st 00:20:00 /tn "espsyncdata" /tr "D:\wamp64\www\amzcount\atuotask\esp_run.bat"
SCHTASKS /Create /sc daily /st 00:25:00 /tn "itsyncdata" /tr "D:\wamp64\www\amzcount\atuotask\it_run.bat"
SCHTASKS /Create /sc daily /st 00:30:00 /tn "frsyncdata" /tr "D:\wamp64\www\amzcount\atuotask\fr_run.bat"
SCHTASKS /Create /sc daily /st 00:35:00 /tn "mxsyncdata" /tr "D:\wamp64\www\amzcount\atuotask\mx_run.bat"
SCHTASKS /Create /sc daily /st 00:40:00 /tn "casyncdata" /tr "D:\wamp64\www\amzcount\atuotask\ca_run.bat"